/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil, tenant, unidade e permissoes efetivas do usuario autenticado */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista Brand Kits do tenant */
        get: operations["listBrandProfiles"];
        put?: never;
        /** Cria Brand Kit */
        post: operations["createBrandProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contas externas conectadas
         * @description Nunca retorna token, refresh token ou qualquer segredo.
         */
        get: operations["listConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inicia fluxo OAuth para um provedor
         * @description Devolve a URL de autorizacao oficial do provedor. O app apenas abre essa URL.
         *     O callback e recebido pelo backend; o token nunca transita pelo aplicativo.
         */
        post: operations["startOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoga a conexao e o segredo associado */
        delete: operations["revokeConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connectionId}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capacidades comprovadas para esta conta, pais e versao de API
         * @description Fonte da verdade para a interface. O app so oferece acao com `supported = true`.
         *     Capacidade sem `verified_at` recente e tratada como indisponivel.
         */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submete briefing e cria campanha em DRAFT */
        post: operations["submitBrief"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista campanhas do tenant */
        get: operations["listCampaigns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe da campanha, com estado reconciliado */
        get: operations["getCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ultima versao do plano proposto
         * @description Conforme campaign-plan.schema.json. Inclui proveniencia da IA e justificativa.
         */
        get: operations["getCampaignPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/plan/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solicita nova versao do plano com ajustes do usuario */
        post: operations["regeneratePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Valida plano contra politica, orcamento e capacidades
         * @description Nao produz efeito externo. Emite `policy_decision_id` quando aprovavel.
         *     Este e o unico caminho para obter autorizacao de publicacao.
         */
        post: operations["validateCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publica nas contas autorizadas
         * @description Exige `policy_decision_id` valido e nao expirado, aprovacao humana registrada e
         *     `Idempotency-Key`. Responde 202: publicacao e assincrona e so vira ACTIVE apos
         *     reconciliacao com ID externo confirmado por canal.
         */
        post: operations["publishCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pausa a campanha em todos os canais */
        post: operations["pauseCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Altera orcamento
         * @description Aumento relevante exige aprovacao humana e step-up. Variacao percentual acima do
         *     limite configurado e recusada com 403, nao "ajustada automaticamente".
         */
        patch: operations["updateBudget"];
        trace?: never;
    };
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aprovacoes pendentes do usuario */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approvalId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprova, rejeita ou pede ajuste
         * @description Registra ator, momento, versao do plano e justificativa na trilha imutavel.
         *     Aprovacao dupla, quando exigida pela politica, so se completa com dois atores distintos.
         */
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nivel de autonomia vigente e limites */
        get: operations["getAutonomy"];
        /**
         * Altera nivel de autonomia
         * @description Sempre exige aprovacao humana e step-up, em qualquer nivel atual.
         */
        put: operations["setAutonomy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aciona parada de emergencia
         * @description Escopos: CAMPAIGN, ACCOUNT, TENANT, PLATFORM, GLOBAL.
         *     E o unico caminho que dispensa fila normal de decisao, porque so REDUZ efeito.
         *     Nunca pode ampliar efeito. Ainda assim gera evento e auditoria.
         */
        post: operations["activateKillSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metricas reconciliadas da campanha */
        get: operations["getInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trilha de auditoria do tenant */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Provider: "GOOGLE_ADS" | "META" | "WHATSAPP";
        /** @enum {string} */
        Channel: "GOOGLE_ADS" | "META_FACEBOOK" | "META_INSTAGRAM" | "WHATSAPP";
        /** @enum {string} */
        CampaignState: "DRAFT" | "STRATEGY_READY" | "ASSETS_READY" | "VALIDATED" | "AWAITING_APPROVAL" | "APPROVED" | "PUBLISHING" | "ACTIVE" | "OPTIMIZING" | "PAUSED" | "COMPLETED" | "FAILED";
        Error: {
            /**
             * @description Taxonomia canonica. Codigos de provedor NUNCA vazam para o cliente.
             * @enum {string}
             */
            code: "UNAUTHENTICATED" | "PERMISSION_DENIED" | "STEP_UP_REQUIRED" | "APPROVAL_REQUIRED" | "VALIDATION_FAILED" | "INVALID_STATE" | "CAPABILITY_UNSUPPORTED" | "BUDGET_LIMIT" | "RATE_LIMITED" | "QUOTA_EXHAUSTED" | "POLICY_VIOLATION" | "KILL_SWITCH_ACTIVE" | "NOT_FOUND" | "TRANSIENT" | "UNKNOWN";
            /** @description Texto compreensivel por usuario nao tecnico. */
            message: string;
            details?: Record<string, never> | null;
            /**
             * Format: uri
             * @description Quando a API do provedor nao permite a acao, aponta o portal oficial. Nunca simular sucesso.
             */
            assisted_flow_url?: string | null;
        };
        Me: {
            /** Format: uuid */
            user_id?: string;
            /** Format: uuid */
            tenant_id?: string;
            /** Format: uuid */
            business_unit_id?: string | null;
            roles?: string[];
            permissions?: string[];
            mfa_enabled?: boolean;
        };
        BrandProfileInput: {
            name: string;
            tone: string;
            colors?: string[];
            differentiators?: string[];
            /** @description Alimenta o Policy Engine deterministico, nao apenas o prompt. */
            restrictions?: string[];
        };
        BrandProfile: components["schemas"]["BrandProfileInput"] & {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Connection: {
            /** Format: uuid */
            id?: string;
            provider?: components["schemas"]["Provider"];
            external_account_id?: string;
            display_name?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "EXPIRED" | "REVOKED" | "NEEDS_REAUTH";
            api_version?: string;
            /** Format: date-time */
            last_synced_at?: string | null;
        };
        Capability: {
            capability_key?: string;
            supported?: boolean;
            requires_approval?: boolean;
            /** Format: uri */
            evidence_url?: string | null;
            /** Format: date-time */
            verified_at?: string;
            notes?: string | null;
        };
        Campaign: {
            /** Format: uuid */
            id?: string;
            name?: string;
            state?: components["schemas"]["CampaignState"];
            objective?: string;
            channels?: components["schemas"]["Channel"][];
            /** @description Vazio ate a reconciliacao confirmar. Estado ACTIVE exige ao menos um ID externo. */
            external_resources?: {
                channel?: components["schemas"]["Channel"];
                external_resource_id?: string;
                /** @enum {string} */
                sync_status?: "PENDING" | "CONFIRMED" | "DIVERGENT";
                /** Format: date-time */
                last_synced_at?: string | null;
            }[];
            budget?: {
                currency?: string;
                total_amount?: number;
                daily_cap?: number;
                spent_to_date?: number;
            };
            /** Format: date-time */
            created_at?: string;
        };
        PolicyDecision: {
            /** Format: uuid */
            policy_decision_id?: string | null;
            /** @enum {string} */
            outcome?: "APPROVABLE" | "BLOCKED" | "NEEDS_CHANGES";
            /** Format: date-time */
            expires_at?: string | null;
            requires_human_approval?: boolean;
            requires_dual_approval?: boolean;
            findings?: {
                code?: string;
                /** @enum {string} */
                severity?: "INFO" | "WARNING" | "BLOCKING";
                explanation?: string;
            }[];
        };
        ApprovalRequest: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            campaign_id?: string;
            /** @description Gatilho que exigiu aprovacao humana. */
            reason?: string;
            plan_version?: number;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "REJECTED" | "CHANGES_REQUESTED" | "EXPIRED";
            requires_dual_approval?: boolean;
            decided_by?: string[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        AutonomySettings: {
            level?: number;
            /** @enum {string} */
            level_label?: "ASSISTENTE" | "APROVADO" | "LIMITADO" | "OPERACIONAL";
            /** @description Gatilhos que exigem humano em QUALQUER nivel. */
            always_require_human?: string[];
            max_budget_change_pct?: number;
            /** Format: date-time */
            updated_at?: string;
        };
        InsightSeries: {
            /** Format: uuid */
            campaign_id?: string;
            /** Format: date-time */
            last_synced_at?: string | null;
            points?: {
                /** Format: date */
                date?: string;
                channel?: components["schemas"]["Channel"];
                impressions?: number;
                clicks?: number;
                spend?: number;
                conversions?: number;
                cpa?: number | null;
            }[];
        };
        AuditEvent: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            occurred_at?: string;
            /** @enum {string} */
            actor_kind?: "USER" | "SYSTEM" | "AI" | "EXTERNAL_PROVIDER";
            /** Format: uuid */
            actor_id?: string | null;
            action?: string;
            target?: string;
            /** Format: uuid */
            policy_decision_id?: string | null;
            evidence?: Record<string, never> | null;
        };
    };
    responses: {
        /** @description Nao autenticado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Nao encontrado neste tenant */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Payload invalido segundo o schema canonico */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Transicao de estado nao permitida pela maquina de estados */
        InvalidState: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Reautenticacao necessaria */
        StepUpRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Aprovacao humana ausente, invalida ou expirada */
        ApprovalRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
        IdempotencyKey: string;
        /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
        StepUpToken: string;
        CampaignId: string;
        ConnectionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listBrandProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfile"][];
                };
            };
        };
    };
    createBrandProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandProfileInput"];
            };
        };
        responses: {
            /** @description Criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfile"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listConnections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"][];
                };
            };
        };
    };
    startOAuth: {
        parameters: {
            query?: never;
            header: {
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    provider: components["schemas"]["Provider"];
                };
            };
        };
        responses: {
            /** @description URL de autorizacao */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        authorization_url: string;
                        state: string;
                    };
                };
            };
            403: components["responses"]["StepUpRequired"];
        };
    };
    revokeConnection: {
        parameters: {
            query?: never;
            header: {
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                connectionId: components["parameters"]["ConnectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revogada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["StepUpRequired"];
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectionId: components["parameters"]["ConnectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capability"][];
                };
            };
        };
    };
    submitBrief: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        /** @description Conforme campaign-brief.schema.json, sem tenant_id (derivado do token). */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Aceito; geracao de estrategia em andamento */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listCampaigns: {
        parameters: {
            query?: {
                state?: components["schemas"]["CampaignState"];
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Campaign"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    getCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCampaignPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    regeneratePlan: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    adjustments?: string;
                };
            };
        };
        responses: {
            /** @description Geracao iniciada */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["InvalidState"];
        };
    };
    validateCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado da validacao */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDecision"];
                };
            };
            409: components["responses"]["InvalidState"];
        };
    };
    publishCampaign: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
            };
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    policy_decision_id: string;
                    /** Format: uuid */
                    approval_id: string;
                };
            };
        };
        responses: {
            /** @description Publicacao iniciada (Saga aberta) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            403: components["responses"]["ApprovalRequired"];
            409: components["responses"]["InvalidState"];
            422: components["responses"]["ValidationError"];
        };
    };
    pauseCampaign: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pausa solicitada */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBudget: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
            };
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    daily_cap: number;
                    total_amount?: number;
                    /** Format: uuid */
                    approval_id: string;
                };
            };
        };
        responses: {
            /** @description Alteracao aceita */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["ApprovalRequired"];
        };
    };
    listApprovals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"][];
                };
            };
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
            };
            path: {
                approvalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "APPROVE" | "REJECT" | "REQUEST_CHANGES";
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Decisao registrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"];
                };
            };
            403: components["responses"]["StepUpRequired"];
            /** @description Decisao ja registrada ou aprovador nao elegivel */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAutonomy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutonomySettings"];
                };
            };
        };
    };
    setAutonomy: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    level: number;
                    /** Format: uuid */
                    approval_id: string;
                };
            };
        };
        responses: {
            /** @description Alterado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutonomySettings"];
                };
            };
            403: components["responses"]["ApprovalRequired"];
        };
    };
    activateKillSwitch: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    scope: "CAMPAIGN" | "ACCOUNT" | "TENANT" | "PLATFORM" | "GLOBAL";
                    /** Format: uuid */
                    target_id?: string | null;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Acionado; pausa propagando */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getInsights: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightSeries"];
                };
            };
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                campaign_id?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["AuditEvent"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
}
