/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inicia o fluxo OIDC Authorization Code + PKCE. Redireciona o navegador ao authorization_endpoint do provedor de identidade configurado (real, via CAMPAIA_OIDC_*, ou o provedor de teste fail-closed em CAMPAIA_ENV=test|local_dev). */
        get: operations["startLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback do provedor de identidade. Troca o codigo de autorizacao (com PKCE), verifica a assinatura e as claims do ID token, e estabelece uma sessao real (cookies `campaia_session` HttpOnly/Secure e `campaia_csrf`). */
        get: operations["authCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoga a sessao atual (se houver) e limpa os cookies de sessao/CSRF. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil, tenant, unidade e permissoes efetivas do usuario autenticado */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os tenants dos quais o usuario autenticado e realmente membro (WP-03), sempre incluindo o tenant ativo da sessao atual. Exige sessao Web real (`cookieAuth`) -- nunca disponivel via o fixture `bearerAuth`, que nao carrega sessao alguma para enumerar. */
        get: operations["getSessionMemberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/switch-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Troca o tenant ativo da sessao para um dos memberships reais do usuario (WP-03). Reemite a sessao (novo cookie `campaia_session`/`campaia_csrf`, mesma disciplina de rotacao do login) e invalida qualquer step-up recente em TODOS os tenants do usuario, nao apenas no que esta sendo deixado. */
        post: operations["switchTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brand-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista Brand Kits do tenant */
        get: operations["listBrandProfiles"];
        put?: never;
        /** Cria Brand Kit */
        post: operations["createBrandProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contas externas conectadas
         * @description Nunca retorna token, refresh token ou qualquer segredo.
         */
        get: operations["listConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inicia fluxo OAuth para um provedor
         * @description Devolve a URL de autorizacao oficial do provedor. O app apenas abre essa URL.
         *     O callback e recebido pelo backend; o token nunca transita pelo aplicativo.
         */
        post: operations["startOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/oauth/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finaliza o fluxo OAuth iniciado por /connections/oauth/start (WP-04)
         * @description Simula o que o callback do provedor real devolveria: a conta escolhida pelo usuario
         *     apos a autorizacao. `state` precisa ser o valor devolvido por um /connections/oauth/start
         *     anterior, ainda nao consumido e do mesmo tenant -- nunca aceito de outra origem.
         *     Cria a Connection de fato (o /start sozinho nunca cria uma).
         */
        post: operations["completeOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoga a conexao e o segredo associado */
        delete: operations["revokeConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connectionId}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capacidades comprovadas para esta conta, pais e versao de API
         * @description Fonte da verdade para a interface. O app so oferece acao com `supported = true`.
         *     Capacidade sem `verified_at` recente e tratada como indisponivel.
         */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submete briefing e cria campanha em DRAFT */
        post: operations["submitBrief"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista campanhas do tenant */
        get: operations["listCampaigns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe da campanha, com estado reconciliado */
        get: operations["getCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ultima versao do plano proposto
         * @description Conforme campaign-plan.schema.json. Inclui proveniencia da IA e justificativa.
         */
        get: operations["getCampaignPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/plan/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solicita nova versao do plano com ajustes do usuario */
        post: operations["regeneratePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Valida plano contra politica, orcamento e capacidades
         * @description Nao produz efeito externo. Emite `policy_decision_id` quando aprovavel.
         *     Este e o unico caminho para obter autorizacao de publicacao.
         */
        post: operations["validateCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publica nas contas autorizadas
         * @description Exige `policy_decision_id` valido e nao expirado, aprovacao humana registrada e
         *     `Idempotency-Key`. Responde 202: publicacao e assincrona e so vira ACTIVE apos
         *     reconciliacao com ID externo confirmado por canal.
         */
        post: operations["publishCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pausa a campanha em todos os canais */
        post: operations["pauseCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Altera orcamento
         * @description Aumento relevante exige aprovacao humana e step-up. Variacao percentual acima do
         *     limite configurado e recusada com 403, nao "ajustada automaticamente".
         */
        patch: operations["updateBudget"];
        trace?: never;
    };
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aprovacoes pendentes do usuario */
        get: operations["listApprovals"];
        put?: never;
        /**
         * Registra um novo pedido de aprovacao PENDING
         * @description Nao documentado na paráfrase original do contrato, embora ja implementado e
         *     exercitado desde o WP-05 (achado corrigido aqui, mesma classe dos achados de
         *     campo ausente do WP-05/WP-06): sem esta rota, POST .../publish, PATCH .../budget
         *     e a alteracao de nivel de autonomia nao tem como referenciar uma aprovacao "ja
         *     registrada", pois nenhuma outra rota cria uma. Nao produz nenhum efeito de
         *     dominio por si so -- apenas registra um ApprovalRequest PENDING.
         */
        post: operations["createApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approvalId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprova, rejeita ou pede ajuste
         * @description Registra ator, momento, versao do plano e justificativa na trilha imutavel.
         *     Aprovacao dupla, quando exigida pela politica, so se completa com dois atores distintos.
         */
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nivel de autonomia vigente e limites */
        get: operations["getAutonomy"];
        /**
         * Altera nivel de autonomia
         * @description Sempre exige aprovacao humana e step-up, em qualquer nivel atual.
         */
        put: operations["setAutonomy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aciona parada de emergencia
         * @description Escopos: CAMPAIGN, ACCOUNT, TENANT, PLATFORM, GLOBAL.
         *     E o unico caminho que dispensa fila normal de decisao, porque so REDUZ efeito.
         *     Nunca pode ampliar efeito. Ainda assim gera evento e auditoria.
         */
        post: operations["activateKillSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metricas reconciliadas da campanha */
        get: operations["getInsights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trilha de auditoria do tenant */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Provider: "GOOGLE_ADS" | "META" | "WHATSAPP";
        /** @enum {string} */
        Channel: "GOOGLE_ADS" | "META_FACEBOOK" | "META_INSTAGRAM" | "WHATSAPP";
        /** @enum {string} */
        CampaignState: "DRAFT" | "STRATEGY_READY" | "ASSETS_READY" | "VALIDATED" | "AWAITING_APPROVAL" | "APPROVED" | "PUBLISHING" | "ACTIVE" | "OPTIMIZING" | "PAUSED" | "COMPLETED" | "FAILED";
        Error: {
            /**
             * @description Taxonomia canonica. Codigos de provedor NUNCA vazam para o cliente.
             * @enum {string}
             */
            code: "UNAUTHENTICATED" | "PERMISSION_DENIED" | "STEP_UP_REQUIRED" | "APPROVAL_REQUIRED" | "VALIDATION_FAILED" | "INVALID_STATE" | "CAPABILITY_UNSUPPORTED" | "BUDGET_LIMIT" | "RATE_LIMITED" | "QUOTA_EXHAUSTED" | "POLICY_VIOLATION" | "KILL_SWITCH_ACTIVE" | "NOT_FOUND" | "TRANSIENT" | "UNKNOWN";
            /** @description Texto compreensivel por usuario nao tecnico. */
            message: string;
            details?: Record<string, never> | null;
            /**
             * Format: uri
             * @description Quando a API do provedor nao permite a acao, aponta o portal oficial. Nunca simular sucesso.
             */
            assisted_flow_url?: string | null;
        };
        Me: {
            /** Format: uuid */
            user_id?: string;
            /** Format: uuid */
            tenant_id?: string;
            /** Format: uuid */
            business_unit_id?: string | null;
            roles?: string[];
            permissions?: string[];
            mfa_enabled?: boolean;
        };
        Membership: {
            /** Format: uuid */
            tenant_id?: string;
            /** Format: uuid */
            business_unit_id?: string | null;
            roles?: string[];
            /** @description True para exatamente um membership -- o tenant ativo da sessao atual. */
            is_active?: boolean;
        };
        SessionMemberships: {
            memberships?: components["schemas"]["Membership"][];
        };
        SwitchTenantInput: {
            /**
             * Format: uuid
             * @description Deve ser o tenant_id de um dos memberships reais do usuario (ver GET /session/memberships) -- qualquer outro valor recebe 403.
             */
            tenant_id: string;
        };
        BrandProfileInput: {
            name: string;
            tone: string;
            colors?: string[];
            differentiators?: string[];
            /** @description Alimenta o Policy Engine deterministico, nao apenas o prompt. */
            restrictions?: string[];
        };
        BrandProfile: components["schemas"]["BrandProfileInput"] & {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Connection: {
            /** Format: uuid */
            id?: string;
            provider?: components["schemas"]["Provider"];
            external_account_id?: string;
            display_name?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "EXPIRED" | "REVOKED" | "NEEDS_REAUTH";
            api_version?: string;
            /** Format: date-time */
            last_synced_at?: string | null;
        };
        Capability: {
            provider?: components["schemas"]["Provider"];
            capability_key?: string;
            /**
             * @description Campo real, sempre presente na resposta (api/models.py CapabilityResponse.country),
             *     ausente do contrato ate esta correcao (achado do WP-09, mesma classe dos achados
             *     requested_by/kind/amount/max_level_allowed/business_unit_id dos WP-05 a WP-07).
             */
            country?: string;
            /**
             * @description Campo real, sempre presente na resposta (CapabilityResponse.api_version), ausente
             *     do contrato ate esta correcao (achado do WP-09).
             */
            api_version?: string;
            supported?: boolean;
            requires_approval?: boolean;
            /** Format: uri */
            evidence_url?: string | null;
            /** Format: date-time */
            verified_at?: string;
            notes?: string | null;
        };
        Campaign: {
            /** Format: uuid */
            id?: string;
            /**
             * Format: uuid
             * @description Campo real, sempre presente na resposta (backend/api/models.py CampaignResponse.
             *     business_unit_id), ausente do contrato ate esta correcao (achado do WP-07, mesma
             *     classe dos achados requested_by/kind/amount/max_level_allowed dos WP-05/06/07).
             */
            business_unit_id?: string | null;
            name?: string;
            state?: components["schemas"]["CampaignState"];
            objective?: string;
            /**
             * @description Campo real, sempre presente na resposta (backend/api/models.py CampaignResponse.
             *     brief) -- o corpo do briefing original que criou a campanha (POST /briefs),
             *     reserializado. Ausente do contrato ate esta correcao (achado do WP-01 a WP-11 mais
             *     tardio a ser fechado, mesma classe P-39). Forma nao tipada aqui, como ja acontece
             *     com o campo `plan` de GET /campaigns/{id}/plan.
             */
            brief?: Record<string, never>;
            /**
             * @description Campo real, sempre presente na resposta (backend/api/models.py CampaignResponse.
             *     plan_version). Ausente do contrato ate esta correcao (achado P-39).
             */
            plan_version?: number;
            /**
             * Format: uuid
             * @description Campo real, sempre presente na resposta (backend/api/models.py CampaignResponse.
             *     connection_id). Ausente do contrato ate esta correcao (achado P-39).
             */
            connection_id?: string | null;
            channels?: components["schemas"]["Channel"][];
            /** @description Vazio ate a reconciliacao confirmar. Estado ACTIVE exige ao menos um ID externo. */
            external_resources?: {
                channel?: components["schemas"]["Channel"];
                external_resource_id?: string;
                /** @enum {string} */
                sync_status?: "PENDING" | "CONFIRMED" | "DIVERGENT";
                /** Format: date-time */
                last_synced_at?: string | null;
            }[];
            budget?: {
                currency?: string;
                total_amount?: number;
                daily_cap?: number;
                spent_to_date?: number;
            };
            /**
             * Format: date-time
             * @description Campo real, sempre presente na resposta (backend/api/models.py CampaignResponse.
             *     last_synced_at). Ausente do contrato ate esta correcao (achado P-39).
             */
            last_synced_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        PolicyDecision: {
            /** Format: uuid */
            policy_decision_id?: string | null;
            /** @enum {string} */
            outcome?: "APPROVABLE" | "BLOCKED" | "NEEDS_CHANGES";
            /** Format: date-time */
            expires_at?: string | null;
            requires_human_approval?: boolean;
            requires_dual_approval?: boolean;
            findings?: {
                code?: string;
                /** @enum {string} */
                severity?: "INFO" | "WARNING" | "BLOCKING";
                explanation?: string;
            }[];
        };
        ApprovalRequest: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            campaign_id?: string;
            /**
             * @description O que esta aprovacao decide -- campo real, sempre presente na resposta (ver
             *     api/helpers.py serialize_approval / api/models.py ApprovalResponse, onde ja
             *     era descrito como "extra, not in the contract"), adicionado formalmente ao
             *     contrato no WP-06 apos achado de que a Web precisa distinguir pedidos de
             *     aprovacao por tipo (ex. BUDGET_CHANGE vs. PUBLISH) de forma tipada, nao por
             *     correspondencia fragil de texto em `reason`.
             * @enum {string}
             */
            kind?: "PUBLISH" | "BUDGET_CHANGE" | "AUTONOMY_CHANGE";
            /** @description Gatilho que exigiu aprovacao humana. */
            reason?: string;
            /**
             * Format: uuid
             * @description Quem propos a acao que gerou esta aprovacao (campaign_id.created_by ou
             *     equivalente) -- campo real, sempre presente na resposta (ver
             *     api/helpers.py serialize_approval), adicionado ao contrato no WP-05 apos
             *     achado de campo ausente durante a construcao da tela de aprovacoes.
             *     Necessario para a UI comunicar segregacao de funcoes (quem propos nao
             *     aprova a propria proposta, campaia_core.permissions.can_approve).
             */
            requested_by?: string;
            plan_version?: number;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "REJECTED" | "CHANGES_REQUESTED" | "EXPIRED";
            /**
             * @description Valor associado a este pedido de aprovacao quando aplicavel (ex.: o novo
             *     daily_cap proposto para um BUDGET_CHANGE) -- campo real, sempre presente na
             *     resposta (ver api/helpers.py serialize_approval), ausente do contrato ate
             *     esta correcao (achado do WP-06, mesma classe do achado requested_by do
             *     WP-05). Necessario para a Web aplicar de fato uma alteracao de orcamento ja
             *     aprovada, sem reconstruir o valor de outra origem.
             */
            amount?: string | null;
            requires_dual_approval?: boolean;
            decided_by?: string[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        AutonomySettings: {
            level?: number;
            /** @enum {string} */
            level_label?: "ASSISTENTE" | "APROVADO" | "LIMITADO" | "OPERACIONAL";
            /**
             * @description Teto contratado (campaia_core/autonomy.py AutonomySettings.max_level_allowed)
             *     -- campo real, sempre presente na resposta, ausente do contrato ate esta
             *     correcao (achado do WP-07, mesma classe dos achados requested_by/kind/amount
             *     dos WP-05/06). O nivel nunca pode ser configurado acima deste teto (invariante
             *     I-11, guarda contra auto-promocao) -- nao e ajustavel por esta API.
             */
            max_level_allowed?: number;
            /** @description Gatilhos que exigem humano em QUALQUER nivel. */
            always_require_human?: string[];
            max_budget_change_pct?: number;
            /** Format: date-time */
            updated_at?: string;
        };
        /**
         * @description Corpo de resposta real do 202 de POST /kill-switch (api/routes_campaigns.py
         *     _do_kill_switch) -- ausente do contrato ate esta correcao (achado do WP-08, mesma
         *     classe dos achados anteriores: campo/schema real, sempre devolvido, nunca
         *     documentado).
         */
        KillSwitchResult: {
            /** @enum {string} */
            scope?: "CAMPAIGN" | "ACCOUNT" | "TENANT" | "PLATFORM" | "GLOBAL";
            affected_campaign_ids?: string[];
        };
        InsightSeries: {
            /** Format: uuid */
            campaign_id?: string;
            /** Format: date-time */
            last_synced_at?: string | null;
            points?: {
                /** Format: date */
                date?: string;
                channel?: components["schemas"]["Channel"];
                impressions?: number;
                clicks?: number;
                spend?: number;
                conversions?: number;
                cpa?: number | null;
            }[];
            note?: string;
        };
        AuditEvent: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            occurred_at?: string;
            /** @enum {string} */
            actor_kind?: "USER" | "SYSTEM" | "AI" | "EXTERNAL_PROVIDER";
            /** Format: uuid */
            actor_id?: string | null;
            action?: string;
            target?: string;
            /** Format: uuid */
            policy_decision_id?: string | null;
            evidence?: Record<string, never> | null;
        };
    };
    responses: {
        /** @description Nao autenticado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Nao encontrado neste tenant */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Payload invalido segundo o schema canonico */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Transicao de estado nao permitida pela maquina de estados */
        InvalidState: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Reautenticacao necessaria */
        StepUpRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Aprovacao humana ausente, invalida ou expirada */
        ApprovalRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operacao recusada pela autorizacao do servidor (ex.: tenant_id que nao e um membership real do usuario autenticado). */
        PermissionDenied: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
        IdempotencyKey: string;
        /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
        StepUpToken: string;
        CampaignId: string;
        ConnectionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startLogin: {
        parameters: {
            query?: {
                /** @description Caminho relativo same-origin para redirecionar apos login bem-sucedido (default `/`). Qualquer valor absoluto ou iniciado por `//` e ignorado (protecao contra open redirect). */
                redirect_after_login?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirecionamento ao authorization_endpoint do provedor de identidade. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nenhum provedor de identidade configurado. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    authCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessao estabelecida; redireciona para `redirect_after_login`. */
            302: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessao revogada; redireciona para `/`. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSessionMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMemberships"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    switchTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchTenantInput"];
            };
        };
        responses: {
            /** @description Sessao trocada com sucesso; cookies reemitidos. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMemberships"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["PermissionDenied"];
        };
    };
    listBrandProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfile"][];
                };
            };
        };
    };
    createBrandProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandProfileInput"];
            };
        };
        responses: {
            /** @description Criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfile"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listConnections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"][];
                };
            };
        };
    };
    startOAuth: {
        parameters: {
            query?: never;
            header: {
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    provider: components["schemas"]["Provider"];
                };
            };
        };
        responses: {
            /** @description URL de autorizacao */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        authorization_url: string;
                        state: string;
                    };
                };
            };
            403: components["responses"]["StepUpRequired"];
        };
    };
    completeOAuth: {
        parameters: {
            query?: never;
            header: {
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    state: string;
                    external_account_id: string;
                    display_name: string;
                };
            };
        };
        responses: {
            /** @description Conexao criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["StepUpRequired"];
        };
    };
    revokeConnection: {
        parameters: {
            query?: never;
            header: {
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                connectionId: components["parameters"]["ConnectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revogada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["StepUpRequired"];
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectionId: components["parameters"]["ConnectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capability"][];
                };
            };
        };
    };
    submitBrief: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        /** @description Conforme campaign-brief.schema.json, sem tenant_id (derivado do token). */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Aceito; geracao de estrategia em andamento */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    listCampaigns: {
        parameters: {
            query?: {
                state?: components["schemas"]["CampaignState"];
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Campaign"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    getCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCampaignPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    regeneratePlan: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    adjustments?: string;
                };
            };
        };
        responses: {
            /** @description Geracao iniciada */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["InvalidState"];
        };
    };
    validateCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado da validacao */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDecision"];
                };
            };
            409: components["responses"]["InvalidState"];
        };
    };
    publishCampaign: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
            };
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    policy_decision_id: string;
                    /** Format: uuid */
                    approval_id: string;
                };
            };
        };
        responses: {
            /** @description Publicacao iniciada (Saga aberta) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            403: components["responses"]["ApprovalRequired"];
            409: components["responses"]["InvalidState"];
            422: components["responses"]["ValidationError"];
        };
    };
    pauseCampaign: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pausa solicitada */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBudget: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
            };
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    daily_cap: number;
                    total_amount?: number;
                    /** Format: uuid */
                    approval_id: string;
                };
            };
        };
        responses: {
            /** @description Alteracao aceita */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["ApprovalRequired"];
        };
    };
    listApprovals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"][];
                };
            };
        };
    };
    createApproval: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    campaign_id: string;
                    /** @enum {string} */
                    kind: "PUBLISH" | "BUDGET_CHANGE" | "AUTONOMY_CHANGE";
                    /** @description Valor associado ao pedido quando aplicavel (ex. novo daily_cap para BUDGET_CHANGE). */
                    amount?: number | null;
                    /** @default false */
                    requires_dual_approval?: boolean;
                };
            };
        };
        responses: {
            /** @description Aprovacao registrada, PENDING */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
            };
            path: {
                approvalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "APPROVE" | "REJECT" | "REQUEST_CHANGES";
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Decisao registrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"];
                };
            };
            403: components["responses"]["StepUpRequired"];
            /** @description Decisao ja registrada ou aprovador nao elegivel */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAutonomy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutonomySettings"];
                };
            };
        };
    };
    setAutonomy: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Prova de reautenticacao recente. Exigido em conexao de conta, verba, autonomia e aprovacao. */
                "X-Step-Up-Token": components["parameters"]["StepUpToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    level: number;
                    /** Format: uuid */
                    approval_id: string;
                };
            };
        };
        responses: {
            /** @description Alterado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutonomySettings"];
                };
            };
            403: components["responses"]["ApprovalRequired"];
        };
    };
    activateKillSwitch: {
        parameters: {
            query?: never;
            header: {
                /** @description Repetir o mesmo valor NAO duplica o efeito; devolve o resultado original. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    scope: "CAMPAIGN" | "ACCOUNT" | "TENANT" | "PLATFORM" | "GLOBAL";
                    /** Format: uuid */
                    target_id?: string | null;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Acionado; pausa propagando */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchResult"];
                };
            };
        };
    };
    getInsights: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightSeries"];
                };
            };
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                campaign_id?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["AuditEvent"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
}
