// Thin, hand-written re-export over the generated contract types.
// This file is NOT generated — it is a stable import surface so the rest
// of the app never imports `bff-openapi.generated.ts` (regenerated by
// `npm run contracts:generate`) directly.
import type { components } from "./bff-openapi.generated";

export type Me = components["schemas"]["Me"];
export type ApiErrorBody = components["schemas"]["Error"];
export type SessionUser = components["schemas"]["SessionUser"];
export type Membership = components["schemas"]["MembershipItem"];
export type MembershipsResponse = components["schemas"]["MembershipsResponse"];
export type BrandProfile = components["schemas"]["BrandProfile"];
export type BrandProfileInput = components["schemas"]["BrandProfileInput"];
export type Connection = components["schemas"]["Connection"];
export type Provider = components["schemas"]["Provider"];
export type Campaign = components["schemas"]["Campaign"];
export type PolicyDecision = components["schemas"]["PolicyDecision"];
export type ApprovalRequest = components["schemas"]["ApprovalRequest"];
