// Thin, hand-written re-export over the generated contract types.
// This file is NOT generated — it is a stable import surface so the rest
// of the app never imports `bff-openapi.generated.ts` (regenerated by
// `npm run contracts:generate`) directly.
import type { components } from "./bff-openapi.generated";

export type Me = components["schemas"]["Me"];
export type ApiErrorBody = components["schemas"]["Error"];
export type SessionUser = components["schemas"]["SessionUser"];
export type Membership = components["schemas"]["MembershipItem"];
export type MembershipsResponse = components["schemas"]["MembershipsResponse"];
